@startuml
left to right direction
actor User 
actor Expert

package "RideRecon System" as System {
    usecase "Provide Input" as ProvideInput
    usecase "Text Input" as TextInput
    usecase "Image Input" as ImageInput
    usecase "Identify Car" as IdentifyCar
    usecase "Resolve Conflicts" as ResolveConflicts
    usecase "Provide Car Fact" as ProvideCarFact
    usecase "Provide Purchase Sources" as ProvidePurchaseSources
}

actor "Vertex AI Image Model" as VertexAIImageModel
actor "Reverse Image Search" as ReverseImageSearch
actor "4o-mini Text LLM" as TextLLM
actor "Trained ML Model" as TrainedMLModel
actor "Car Dealerships" as Sources

User --> ProvideInput
ProvideInput ..> TextInput : <<include>>
ProvideInput ..> ImageInput : <<include>>

Expert --> IdentifyCar
Expert <|-- VertexAIImageModel
Expert <|-- ReverseImageSearch
Expert <|-- TextLLM
Expert <|-- TrainedMLModel
@enduml