@startuml
left to right direction
actor User 
actor "Vertex AI Image Model" as VertexAIImageModel
actor "Reverse Image Search" as ReverseImageSearch
actor "4o-mini Text LLM" as TextLLM
actor "Trained ML Model" as TrainedMLModel

package "RideRecon System" as System {
    usecase "Provide Input" as ProvideInput
    usecase "Text Input" as TextInput
    usecase "Image Input" as ImageInput
    usecase "Identify Car" as IdentifyCar
    usecase "Resolve Conflicts" as ResolveConflicts
    usecase "Provide Car Fact" as ProvideCarFact
    usecase "Provide Purchase Sources" as ProvidePurchaseSources
    usecase "Finalize Output" as FinalizeOutput
}

actor Expert as Expert
actor Finalizer as Finalizer

TextLLM --> ProvideCarFact
TextLLM --> ProvidePurchaseSources

User --> ProvideInput
ProvideInput ..> TextInput : <<include>>
ProvideInput ..> ImageInput : <<include>>

Finalizer --> FinalizeOutput
FinalizeOutput ..> ResolveConflicts : <<include>>

Expert --> IdentifyCar
VertexAIImageModel -up-|> Expert
ReverseImageSearch -up-|> Expert
TextLLM -up-|> Expert
TrainedMLModel -up-|> Expert

System -[hidden]-> Expert
System -[hidden]-> Finalizer
@enduml